export const TASKS_FETCH_REQUESTED = 'TASKS_FETCH_REQUESTED';
export const TASKS_FETCH_SUCCEEDED = 'TASKS_FETCH_SUCCEEDED';
export const TASKS_FETCH_FAILED = 'TASKS_FETCH_FAILED';

export const TASK_ADDED = 'TASK_ADDED';
export const TASK_EDITED = 'TASK_EDITED';
export const TASK_REMOVED = 'TASK_REMOVED';

export const CATEGORIES_FETCH_REQUESTED = 'CATEGORIES_FETCH_REQUESTED';
export const CATEGORIES_FETCH_SUCCEEDED = 'CATEGORIES_FETCH_SUCCEEDED';
export const CATEGORIES_FETCH_FAILED = 'CATEGORIES_FETCH_FAILED';